mklink .\deploy\010_waypoints.js ..\src\010_Route_Structure\waypoints.js
mklink .\deploy\011_legs.js ..\src\010_Route_Structure\legs.js
mklink .\deploy\012_route.js ..\src\010_Route_Structure\route.js
mklink .\deploy\013_flightPlan.js ..\src\010_Route_Structure\flightPlan.js
mklink .\deploy\014_airfields.js ..\src\010_Route_Structure\airfields.js
mklink .\deploy\021_legCalculationsSet1.js ..\src\020_Leg_Calculations\legCalculationsSet1.js
mklink .\deploy\021_legCalculationsSet2.js ..\src\020_Leg_Calculations\legCalculationsSet2.js
mklink .\deploy\021_legCalculationsSet3.js ..\src\020_Leg_Calculations\legCalculationsSet3.js
mklink .\deploy\021_legCalculationsSet4.js ..\src\020_Leg_Calculations\legCalculationsSet4.js
mklink .\deploy\031_interfaces.js ..\src\030_Interfaces\interfaces.js
mklink .\deploy\034_generateFlightPlanTextFile.js ..\src\030_Interfaces\generateFlightPlanTextFile.js
mklink .\deploy\034_generateGarminFlightPlan.js ..\src\030_Interfaces\generateGarminFlightPlan.js
mklink .\deploy\034_loadGPX.js ..\src\030_Interfaces\loadGPX.js
mklink .\deploy\035_dumpModel.js ..\src\030_Interfaces\dumpModel.js
mklink .\deploy\041_noaaGeomag.js ..\src\040_Services\noaaGeomag.js
mklink .\deploy\041_ignGeopf.js ..\src\040_Services\ignGeopf.js
mklink .\deploy\041_utilities.js ..\src\040_Services\utilities.js
mklink .\deploy\910_testRouteCreation.js ..\tests\010_testRouteCreation.js
mklink .\deploy\920_testDeclination.js ..\tests\020_testDeclination.js
mklink .\deploy\920_testElevation.js ..\tests\020_testElevation.js
mklink .\deploy\930_testPushLegResults.js ..\tests\030_testPushLegResults.js
mklink .\deploy\920_testWeatherVariables.js ..\tests\020_testWeatherVariables.js
mklink .\deploy\942_testFetchRouteWeatherData.js ..\tests\040_testFetchRouteWeatherData.js

